-- author-historical-pois-batch3.sql — overnight content boost pass 3
-- Hand-authored tour-guide-voice historical_note for 25 more high-value
-- historical POIs along or near the Heritage Trail. Each ~500-1100 chars.
-- When SalemIntelligence catches up its own content will overwrite.

BEGIN;

UPDATE salem_pois SET historical_note = E'You''re standing at 14 Mall Street — the house where Nathaniel Hawthorne wrote The Scarlet Letter. He moved here with his family in 1847 after losing his job at the Custom House in a patronage purge, and from a cramped second-story room he wrote the novel that would make him America''s first great novelist. He finished the manuscript in February 1850. The Scarlet Letter was published that March. Within a year he had left Salem forever, convinced his hometown had shunned him. But the book made Salem immortal.', updated_at = NOW() WHERE id = 'scarlet_letter_house';

UPDATE salem_pois SET historical_note = E'Look around: somewhere on this block stood the home of Alice Parker — a fisherman''s wife swept up in the 1692 hysteria. Accused of witchcraft in May, she was convicted on spectral evidence and hanged on September 22, 1692, alongside seven others — one of the last group to die at Proctor''s Ledge before the crisis collapsed. Her son-in-law John Westgate had been her most hostile accuser, describing strange visions of her in her husband''s tavern. She protested her innocence to the end. The ground you''re walking on held her story.', updated_at = NOW() WHERE id = 'alice_parker_home';

UPDATE salem_pois SET historical_note = E'This is the site of Ann Pudeator''s home. A twice-widowed nurse and healer, Pudeator was in her seventies when she was accused of witchcraft in 1692. Like many midwives in Puritan New England, she knew herbs and folk remedies — and that knowledge became the basis of the accusations against her. She was hanged on September 22, 1692. She was one of the last five people executed before the trials ended. In 1957, long after her death, Massachusetts formally exonerated her name.', updated_at = NOW() WHERE id = 'ann_pudeator_home';

UPDATE salem_pois SET historical_note = E'The Blue Anchor Tavern stood near here in 1692. Taverns were the nerve centers of colonial towns — where news was traded, deals struck, rumors spread, and accusations born. The Blue Anchor saw all of it during the witch trial year. Bridget Bishop, the first person hanged on June 10, 1692, ran her own tavern a few blocks away; her reputation as an unruly tavern-keeper was part of what made her a target. A tavern could make you rich — or it could get you killed. Pause here and imagine the candles, the ale, the low voices, the fear.', updated_at = NOW() WHERE id = 'blue_anchor_tavern';

UPDATE salem_pois SET historical_note = E'Welcome to Castle Dismal — officially the Manning House. Built in the early 1800s and owned by the Manning family, this is where a young Nathaniel Hawthorne spent much of his childhood after his sea-captain father died at sea in Surinam in 1808. His mother moved the family here to live with her Manning relatives. Nathaniel read voraciously in the back parlor, walked the docks, and absorbed the stories that would later become his fiction. He called it Castle Dismal in letters — half ironic, half sincere. The dark timbers and shadowed rooms do nothing to soften that nickname.', updated_at = NOW() WHERE id = 'castle_dismal';

UPDATE salem_pois SET historical_note = E'You''re standing on Central Wharf, the original heart of Salem''s commercial waterfront. Built in the 18th century, it stretched out into the harbor so deep-draft merchant ships could tie up right at the warehouses. In Salem''s golden age — the 1790s to 1820s — ships returned to this wharf from Canton, Calcutta, the West Indies, and Europe, laden with pepper, tea, silks, porcelain, molasses, and rum. Fortunes were counted in the warehouses that lined this pier. Today the waterfront is quiet; then, it was the loudest place in the young United States.', updated_at = NOW() WHERE id = 'central_wharf';

UPDATE salem_pois SET historical_note = E'Charlotte Forten Park honors a remarkable Salem native. Born in Philadelphia in 1837 to a free Black abolitionist family, Charlotte Forten came to Salem in 1854 as a teenager to attend the integrated Higginson Grammar School — one of very few places in America at the time a Black student could receive an academic education alongside white peers. She became the first Black woman to teach white students in the Salem public schools. She later went South during the Civil War to teach emancipated children on the Sea Islands, publishing her diary — one of the most important accounts of the wartime Reconstruction experiment. This small park carries her name forward.', updated_at = NOW() WHERE id = 'charlotte_forten_park';

UPDATE salem_pois SET historical_note = E'You''re entering the Charter Street Historic District — one of the oldest continuously-inhabited streets in English-speaking America. The first settlers laid it out in the 1630s, and the street has carried the same name, roughly the same path, for nearly four centuries. To your left is the Old Burying Point, the oldest cemetery in Salem. To your right, a row of Federal-era and Georgian houses. The Salem Witch Trials Memorial sits embedded in the district. Walk it slowly — every house, every stone, every crack in the pavement has at least two centuries of story under it.', updated_at = NOW() WHERE id = 'charter_street_historic_district';

UPDATE salem_pois SET historical_note = E'The Daniels House, built around 1667, is one of the oldest inns in the United States. Originally a private home for Stephen Daniels, a mariner, it was expanded over the 17th and 18th centuries and converted to a tavern. By 1756 it was a licensed inn, and it has welcomed travelers under one name or another for over two and a half centuries. The first floor rooms still have their original gunstock-posts and low beamed ceilings. Look up — many of the boards holding up the second floor are the same ones Stephen Daniels nailed in place when Charles II was still on the English throne.', updated_at = NOW() WHERE id = 'daniels_house_historic_site';

UPDATE salem_pois SET historical_note = E'Walk out onto Derby Wharf. Two thousand feet long, built starting in 1762 for Elias Hasket Derby, it was once the longest wharf in Salem — long enough for the deepest-drafted ships to unload at any tide. From this pier, Derby''s ships sailed to every major port in the world: Canton, Calcutta, Saint Petersburg, Bordeaux, Havana, Mocha. Derby is often called America''s first millionaire, and this wharf is where his fortune was made. At the far end, the squat lighthouse you can see was added in 1871 to guide ships in as the port''s heyday faded.', updated_at = NOW() WHERE id = 'derby_wharf';

UPDATE salem_pois SET historical_note = E'You''re standing where the First Church Meetinghouse stood in 1692 — the center of Puritan religious life in Salem Village. This is where accused witches were examined. This is where Martha Corey was excommunicated in September 1692, her husband Giles still refusing to plead in his own defense. This is where the community came to pray, to hear sermons, and then to accuse one another. The building is gone. What remains is the ground, and the memory that a crisis of conscience unfolded on this spot — one that eventually swallowed twenty lives.', updated_at = NOW() WHERE id = 'first_church_1692_site';

UPDATE salem_pois SET historical_note = E'This is the site of Judge John Hathorne''s home. Hathorne was one of the magistrates who presided over the witch trial examinations in 1692. He asked the questions. He called the evidence. He was, by all surviving accounts, the most aggressive and accusatory of the judges — he didn''t just weigh testimony, he actively worked to extract confessions. Unlike Judge Samuel Sewall, who later publicly repented, Hathorne never apologized, never retracted, never expressed regret. He is buried a few blocks from here in the Old Burying Point. His great-great-grandson Nathaniel Hawthorne added a ''w'' to the family name to distance himself from him.', updated_at = NOW() WHERE id = 'judge_hathorne_home';

UPDATE salem_pois SET historical_note = E'Welcome to the McIntire Historic District — block after block of Federal-era mansions built in Salem''s golden age, most designed or ornamented by the self-taught Salem woodcarver-turned-architect Samuel McIntire. Between 1780 and 1830, Salem''s merchant princes — captains returning wealthy from the China trade — commissioned McIntire to build houses that would announce their fortunes to the world. The result is one of the finest concentrations of Federal-style architecture in the United States. Walk slowly down Chestnut Street, Essex Street, or Federal Street. Look up. The rooflines, the cornices, the delicate carved garlands and urns — all his hand.', updated_at = NOW() WHERE id = 'mcintire_historic_district';

UPDATE salem_pois SET historical_note = E'This was the home of Nathaniel Bowditch, whose 1802 book The New American Practical Navigator revolutionized sailing. Bowditch — a self-taught Salem native who left school at ten and apprenticed in a ship chandler''s shop — taught himself calculus, Latin, and astronomy by lamplight. He went on to compute tables that let an ordinary sailor calculate longitude at sea accurately. His book is still issued by the U.S. Navy today, more than two centuries later. Every chart, every navigation table Americans use, traces back to a self-taught boy who read math books by candle in a small Salem bedroom.', updated_at = NOW() WHERE id = 'nathaniel_bowditch_house';

UPDATE salem_pois SET historical_note = E'The Peabody Essex Museum — PEM — is the oldest continuously-operating museum in the United States, founded in 1799 as the East India Marine Society by Salem sea captains. At first, it was a society for ship masters who had sailed beyond the Cape of Good Hope or Cape Horn, and their collection was curiosities brought back from Canton, Calcutta, Tahiti, and ports nobody in Salem could yet find on a map. Those original curiosities became one of the great collections of Asian and maritime art in the Americas. Today the PEM owns more than a million objects, including whole buildings — like the Yin Yu Tang merchant''s house moved piece by piece from China and reassembled inside the museum.', updated_at = NOW() WHERE id = 'peabody_essex_museum_2';

UPDATE salem_pois SET historical_note = E'Somewhere near here stood Philip English''s Great House — once the grandest private home in Salem. English was a wealthy merchant, and in 1692 that wealth made him a target. Both he and his wife Mary were accused of witchcraft, but before they could be tried, they escaped — reportedly fleeing to New York with the help of sympathetic friends and the governor''s own connivance. They stayed away until the crisis ended. When they returned, their home had been ransacked by creditors; they spent years suing to recover what had been stolen. The house is gone. The lesson isn''t: even wealth was no shield against the witch panic.', updated_at = NOW() WHERE id = 'philip_english_house';

UPDATE salem_pois SET historical_note = E'This is Ropes Mansion, built around 1727 by the wealthy merchant Samuel Barnard and later home to the Ropes family for more than a century. The elegant gambrel roof and the gabled garden wing are classic colonial Georgian. It gained a second kind of fame in 1993 when Disney used the exterior as the Allison House in the film Hocus Pocus — if you''ve seen the movie, you''ve seen this porch. Walk around to the garden: it''s an early example of New England formal landscape design, restored to its 19th-century form and open to the public. Free to visit, one of the loveliest quiet corners in the city.', updated_at = NOW() WHERE id = 'ropes_mansion_and_garden';

UPDATE salem_pois SET historical_note = E'Salem Harbor. For two hundred years this water was the busiest port in the young United States. In 1789 President George Washington toured Salem expressly to see this harbor — the engine of American wealth at the time. Thirteen countries had official consulates in Salem in 1800. From this harbor, Salem ships sailed to places Americans didn''t yet have names for. Stand at the edge, look east, and picture the forest of masts: at the peak, over a hundred ships at anchor, signal flags snapping, sails being struck, small boats ferrying cargo ashore. The ships are gone. The water remembers.', updated_at = NOW() WHERE id = 'salem_harbor';

UPDATE salem_pois SET historical_note = E'A small bronze plaque marks a turning point in American law and memory. In 1692, this town sent twenty people to their deaths for witchcraft. In 1957 — two hundred sixty-five years later — the Commonwealth of Massachusetts formally apologized. In 1992, on the tercentenary, this plaque and the adjacent memorial were dedicated, with survivors'' descendants present. Read the names. They were neighbors, mothers, grandfathers, children. They died on the word of teenagers and the fear of a community. The plaque is small. The memory should not be.', updated_at = NOW() WHERE id = 'salem_witch_trials_plaque';

UPDATE salem_pois SET historical_note = E'The Scale House, built in 1829, is part of the Salem Maritime National Historic Site and was used by customs officials to weigh cargo coming off the ships. Incoming merchandise — pepper, tea, coffee, cocoa, silks — had duties levied by weight. A cheating scale could cost a captain a fortune or let a government lose one. The instruments inside were precision-made, regulated by federal law, and inspected frequently. It''s a small building, but it represents the invisible machinery of American trade: the weights and measures that made commerce honest.', updated_at = NOW() WHERE id = 'scale_house';

UPDATE salem_pois SET historical_note = E'The schooner Fame you see tied up here is a working replica of a real 1812 Salem privateer — the original Fame captured twenty British merchant ships during the War of 1812. Privateers were privately-owned vessels authorized by Congress to attack enemy shipping, and Salem''s fleet of privateers harassed British trade so effectively that Royal Navy frigates were pulled from other missions to hunt them. This replica, launched in 2003, gives public sails of Salem Harbor — raising the same rigging pattern, hauling the same kind of cannon, carrying visitors where her namesake once carried sailors looking for a prize.', updated_at = NOW() WHERE id = 'schooner_fame_of_salem';

UPDATE salem_pois SET historical_note = E'The Ship Tavern stood near here in 1692 — one of the village''s lesser-known but important gathering places. Taverns played a complicated role during the witch crisis: they were where rumors were traded, where accusations first formed, where the accused were sometimes mocked, and where the accusers gathered. Several examinations of accused witches happened near here. The Ship is long gone. What remains is the understanding that a tavern was as much a political institution in 1692 Salem as a meetinghouse.', updated_at = NOW() WHERE id = 'ship_tavern_site';

UPDATE salem_pois SET historical_note = E'The West India Goods Store, operated by the National Park Service inside Salem Maritime National Historic Site, recreates the kind of shop a 19th-century Salem household would have provisioned from. Ships coming home from the Caribbean and South America brought sugar, molasses, coffee, spices, tropical fruits, and rum; shops like this one retailed those goods to the public at dizzying markups. Step inside if the store is open — the shelves and counter are built to period and the goods are authentic. The smell alone — spices and coffee and old wood — is a time machine.', updated_at = NOW() WHERE id = 'west_india_goods_store';

UPDATE salem_pois SET historical_note = E'The World War II Memorial on Salem Common lists the names of Salem residents who gave their lives in the conflict. Walk its length. Some served in Europe, some in the Pacific, some in convoys across the North Atlantic. For a maritime city with deep Navy traditions, the Pacific names are particularly numerous. Each one was someone''s son, brother, father. Each one walked this Common as a child, the way you''re walking it now. Take a moment.', updated_at = NOW() WHERE id = 'world_war_ii_memorial';

UPDATE salem_pois SET historical_note = E'The Yin Yu Tang House inside the Peabody Essex Museum is a two-hundred-year-old Chinese merchant''s house — the Huang family home from rural Anhui Province. In the early 2000s, with the family''s blessing, the entire wooden structure was disassembled piece by piece, every component labeled, shipped across the Pacific, and reassembled inside this Salem museum. It''s the only complete Qing-dynasty Chinese house of its kind outside China. Walk inside. Every beam, every roof tile, every courtyard stone was once in an Anhui village — now standing in a Massachusetts museum, tracing the long arc of Salem''s connection to China that goes back to the first sea captains of the 1790s.', updated_at = NOW() WHERE id = 'yin_yu_tang_house_peabody_essex_museum';

SELECT id, LENGTH(historical_note) AS hn
FROM salem_pois WHERE id IN (
 'scarlet_letter_house','alice_parker_home','ann_pudeator_home','blue_anchor_tavern',
 'castle_dismal','central_wharf','charlotte_forten_park','charter_street_historic_district',
 'daniels_house_historic_site','derby_wharf','first_church_1692_site','judge_hathorne_home',
 'mcintire_historic_district','nathaniel_bowditch_house','peabody_essex_museum_2',
 'philip_english_house','ropes_mansion_and_garden','salem_harbor',
 'salem_witch_trials_plaque','scale_house','schooner_fame_of_salem','ship_tavern_site',
 'west_india_goods_store','world_war_ii_memorial','yin_yu_tang_house_peabody_essex_museum'
) ORDER BY id;

COMMIT;
