/*
 * WickedSalemWitchCityTour v1.5 — Phase 9X (Session 127)
 * Copyright (c) 2026 Dean Maurice Ellis. All rights reserved.
 */

package com.example.wickedsalemwitchcitytour.content.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One of the 16 history-tile articles backing the "Salem Witch Trials → History"
 * 4×4 grid. Generated by Salem Oracle from the corpus at ~/Development/Salem,
 * edited via the admin web tool, published to bundled assets.
 *
 * Tile order:
 *   1     intro       — Pre-1692 vibe
 *   2-13  month       — Jan..Dec 1692
 *   14    fallout     — 1693 court dissolution + pardons
 *   15    closing     — synthesis
 *   16    epilogue    — NPC outcomes
 */
@Entity(tableName = "salem_witch_trials_articles")
data class WitchTrialsArticle(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "tile_order") val tileOrder: Int,
    @ColumnInfo(name = "tile_kind") val tileKind: String,

    val title: String,
    @ColumnInfo(name = "period_label") val periodLabel: String? = null,
    val teaser: String,
    val body: String,

    @ColumnInfo(name = "related_npc_ids") val relatedNpcIds: String = "[]",
    @ColumnInfo(name = "related_event_ids") val relatedEventIds: String = "[]",
    @ColumnInfo(name = "related_newspaper_dates") val relatedNewspaperDates: String = "[]",

    @ColumnInfo(name = "data_source") val dataSource: String = "salem_oracle",
    val confidence: Float = 0.7f,
    @ColumnInfo(name = "verified_date") val verifiedDate: String? = null,
    @ColumnInfo(name = "generator_model") val generatorModel: String? = null
)
