/*
 * WickedSalemWitchCityTour v1.5 — Phase 9X (Session 127)
 * Copyright (c) 2026 Dean Maurice Ellis. All rights reserved.
 */

package com.example.wickedsalemwitchcitytour.content.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One Salem 1692-era newspaper article for the "Salem Witch Trials →
 * Oracle Newspaper" browser. 202 articles bundled, dated 1691-11-01
 * through 1693-05-09. Source: ~/Development/Salem/data/json/newspapers/
 * (LLM-generated by gemma3:27b on the Salem side).
 *
 * Coexists with `salem_1692_newspapers.json` already used by the Heritage
 * Trail tour's HistoricalHeadlineQueue (different consumer, same source).
 *
 * Crisis phases:
 *   0 = pre-crisis (before March 1692)
 *   1-5 = escalation through trials
 *   6 = aftermath
 */
@Entity(tableName = "salem_witch_trials_newspapers")
data class WitchTrialsNewspaper(
    @PrimaryKey val id: String,
    val date: String,
    @ColumnInfo(name = "day_of_week") val dayOfWeek: String? = null,
    @ColumnInfo(name = "long_date") val longDate: String? = null,
    @ColumnInfo(name = "crisis_phase") val crisisPhase: Int = 0,

    val summary: String? = null,
    val lede: String? = null,
    @ColumnInfo(name = "body_points") val bodyPoints: String = "[]",
    @ColumnInfo(name = "tts_full_text") val ttsFullText: String,

    @ColumnInfo(name = "events_referenced") val eventsReferenced: String = "[]",
    @ColumnInfo(name = "event_count") val eventCount: Int = 0,
    @ColumnInfo(name = "fact_count") val factCount: Int = 0,
    @ColumnInfo(name = "primary_source_count") val primarySourceCount: Int = 0,

    @ColumnInfo(name = "data_source") val dataSource: String = "salem_corpus",
    val confidence: Float = 0.85f,
    @ColumnInfo(name = "verified_date") val verifiedDate: String? = null,
    @ColumnInfo(name = "generator_model") val generatorModel: String? = null,

    /** Short ALL-CAPS 1692-tabloid-style headline (5-8 words). S130 Phase 9X.4b. */
    val headline: String? = null,

    /** Single-sentence "most important event" line shown under the headline. */
    @ColumnInfo(name = "headline_summary") val headlineSummary: String? = null
)
