/*
 * WickedSalemWitchCityTour v1.5 — Phase 9X (Session 127)
 * Copyright (c) 2026 Dean Maurice Ellis. All rights reserved.
 */

package com.example.wickedsalemwitchcitytour.content.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * One Tier-1 or Tier-2 NPC biography for the "Salem Witch Trials → People"
 * roster. ~49 figures total (V1 ships Tier 1 + Tier 2 only). Generated by
 * Salem Oracle, edited via admin tool, published to bundled assets.
 *
 * `id` matches the Salem corpus NPC id (e.g. "rebecca_nurse"). Cross-link
 * markup in body uses [[npc:id]] / [[date:YYYY-MM-DD]] / [[event:id]] /
 * [[newspaper:YYYY-MM-DD]].
 */
@Entity(tableName = "salem_witch_trials_npc_bios")
data class WitchTrialsNpcBio(
    @PrimaryKey val id: String,
    val name: String,
    @ColumnInfo(name = "display_name") val displayName: String? = null,

    val tier: Int,
    val role: String,
    val faction: String? = null,
    @ColumnInfo(name = "born_year") val bornYear: Int? = null,
    @ColumnInfo(name = "died_year") val diedYear: Int? = null,
    @ColumnInfo(name = "age_in_1692") val ageIn1692: Int? = null,
    @ColumnInfo(name = "historical_outcome") val historicalOutcome: String? = null,

    val bio: String,

    @ColumnInfo(name = "related_npc_ids") val relatedNpcIds: String = "[]",
    @ColumnInfo(name = "related_event_ids") val relatedEventIds: String = "[]",
    @ColumnInfo(name = "related_newspaper_dates") val relatedNewspaperDates: String = "[]",

    @ColumnInfo(name = "portrait_asset") val portraitAsset: String? = null,

    @ColumnInfo(name = "data_source") val dataSource: String = "salem_oracle",
    val confidence: Float = 0.7f,
    @ColumnInfo(name = "verified_date") val verifiedDate: String? = null,
    @ColumnInfo(name = "generator_model") val generatorModel: String? = null
)
