/*
 * WickedSalemWitchCityTour v1.5 — Session 147
 * Copyright (c) 2026 Destructive AI Gurus, LLC. All rights reserved.
 */

package com.example.wickedsalemwitchcitytour.ui

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.LruCache
import com.example.locationmapapp.util.DebugLogger
import java.io.IOException

/**
 * Loads per-POI triptych heroes from `assets/heroes/{poi_id}.webp`
 * (800x200 WebP generated by `tools/hero-triptych/generate_full.py`).
 *
 * Resolution:
 *   - [loadTriptychThumb] — leftmost 160x200 slice (panel 1, Katrina cat-POV)
 *     for the narration hero banner's thumbnail (`centerCrop` renders it as a
 *     square portrait).
 *   - [loadTriptychFull] — full 800x200 bitmap for the PoiDetailSheet hero.
 *
 * Both return null on missing asset or decode failure; callers fall back to
 * their own tier.
 */
object HeroAssetLoader {
    private const val TAG = "HeroAssetLoader"
    private const val CACHE_BYTES = 8 * 1024 * 1024

    private val cache = object : LruCache<String, Bitmap>(CACHE_BYTES) {
        override fun sizeOf(key: String, value: Bitmap): Int = value.byteCount
    }

    fun loadTriptychFull(context: Context, poiId: String): Bitmap? {
        val key = "full:$poiId"
        cache.get(key)?.let { return it }
        val bmp = decodeAsset(context, "heroes/$poiId.webp") ?: return null
        cache.put(key, bmp)
        return bmp
    }

    fun loadTriptychThumb(context: Context, poiId: String): Bitmap? {
        val key = "thumb:$poiId"
        cache.get(key)?.let { return it }
        val full = loadTriptychFull(context, poiId) ?: return null
        val slice = sliceLeftPanel(full) ?: return null
        cache.put(key, slice)
        return slice
    }

    /** True if `assets/heroes/{poiId}.webp` exists (O(1) probe via open+close). */
    fun hasTriptych(context: Context, poiId: String): Boolean {
        return try {
            context.assets.open("heroes/$poiId.webp").use { true }
        } catch (_: IOException) {
            false
        }
    }

    private fun sliceLeftPanel(full: Bitmap): Bitmap? {
        if (full.width <= 0 || full.height <= 0) return null
        val panelW = (full.width * 160 / 800).coerceAtLeast(1)
        val panelH = full.height
        return try {
            Bitmap.createBitmap(full, 0, 0, panelW, panelH)
        } catch (t: Throwable) {
            DebugLogger.w(TAG, "sliceLeftPanel failed (${full.width}x${full.height}): ${t.message}")
            null
        }
    }

    /**
     * S255: defensive inSampleSize on hero decode. Heroes ship as 800x200
     * WebP so the normal path uses inSampleSize=1 (no downsample). The
     * defensive cap kicks in only if a future hero ships oversized (e.g.,
     * 1600x400 replacement) — without this, ARGB_8888 at 1600x400 = 2.5 MB
     * each would blow past the 8 MB LRU after 3 entries and OOM under
     * tilt-mode pressure. Two-pass decode: bounds probe + downsample.
     */
    private fun decodeAsset(context: Context, path: String): Bitmap? {
        return try {
            val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
            context.assets.open(path).use { stream ->
                BitmapFactory.decodeStream(stream, null, bounds)
            }
            if (bounds.outWidth <= 0 || bounds.outHeight <= 0) return null

            val opts = BitmapFactory.Options().apply {
                inSampleSize = calcSampleSize(bounds.outWidth, bounds.outHeight)
                inPreferredConfig = Bitmap.Config.ARGB_8888
            }
            context.assets.open(path).use { stream ->
                BitmapFactory.decodeStream(stream, null, opts)
            }
        } catch (_: IOException) {
            null
        } catch (t: Throwable) {
            DebugLogger.w(TAG, "decodeAsset($path) failed: ${t.message}")
            null
        }
    }

    /**
     * Compute a power-of-2 inSampleSize so a decoded bitmap fits within
     * [TARGET_W_MAX] × [TARGET_H_MAX]. Heroes ship at 800×200, so the
     * normal return is 1.
     */
    private fun calcSampleSize(srcW: Int, srcH: Int): Int {
        var sample = 1
        while (srcW / (sample * 2) >= TARGET_W_MAX && srcH / (sample * 2) >= TARGET_H_MAX) {
            sample *= 2
        }
        return sample
    }

    // Canonical hero dimensions (tools/hero-triptych/generate_full.py output).
    private const val TARGET_W_MAX = 800
    private const val TARGET_H_MAX = 200
}
