/*
 * WickedSalemWitchCityTour v1.5 — Session 147
 * Copyright (c) 2026 Dean Maurice Ellis. All rights reserved.
 */

package com.example.wickedsalemwitchcitytour.ui

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.util.LruCache
import com.example.locationmapapp.util.DebugLogger
import java.io.IOException

/**
 * Loads per-POI triptych heroes from `assets/heroes/{poi_id}.webp`
 * (800x200 WebP generated by `tools/hero-triptych/generate_full.py`).
 *
 * Resolution:
 *   - [loadTriptychThumb] — leftmost 160x200 slice (panel 1, Katrina cat-POV)
 *     for the narration hero banner's thumbnail (`centerCrop` renders it as a
 *     square portrait).
 *   - [loadTriptychFull] — full 800x200 bitmap for the PoiDetailSheet hero.
 *
 * Both return null on missing asset or decode failure; callers fall back to
 * their own tier.
 */
object HeroAssetLoader {
    private const val TAG = "HeroAssetLoader"
    private const val CACHE_BYTES = 8 * 1024 * 1024

    private val cache = object : LruCache<String, Bitmap>(CACHE_BYTES) {
        override fun sizeOf(key: String, value: Bitmap): Int = value.byteCount
    }

    fun loadTriptychFull(context: Context, poiId: String): Bitmap? {
        val key = "full:$poiId"
        cache.get(key)?.let { return it }
        val bmp = decodeAsset(context, "heroes/$poiId.webp") ?: return null
        cache.put(key, bmp)
        return bmp
    }

    fun loadTriptychThumb(context: Context, poiId: String): Bitmap? {
        val key = "thumb:$poiId"
        cache.get(key)?.let { return it }
        val full = loadTriptychFull(context, poiId) ?: return null
        val slice = sliceLeftPanel(full) ?: return null
        cache.put(key, slice)
        return slice
    }

    /** True if `assets/heroes/{poiId}.webp` exists (O(1) probe via open+close). */
    fun hasTriptych(context: Context, poiId: String): Boolean {
        return try {
            context.assets.open("heroes/$poiId.webp").use { true }
        } catch (_: IOException) {
            false
        }
    }

    private fun sliceLeftPanel(full: Bitmap): Bitmap? {
        if (full.width <= 0 || full.height <= 0) return null
        val panelW = (full.width * 160 / 800).coerceAtLeast(1)
        val panelH = full.height
        return try {
            Bitmap.createBitmap(full, 0, 0, panelW, panelH)
        } catch (t: Throwable) {
            DebugLogger.w(TAG, "sliceLeftPanel failed (${full.width}x${full.height}): ${t.message}")
            null
        }
    }

    private fun decodeAsset(context: Context, path: String): Bitmap? {
        return try {
            context.assets.open(path).use { stream ->
                BitmapFactory.decodeStream(stream)
            }
        } catch (_: IOException) {
            null
        } catch (t: Throwable) {
            DebugLogger.w(TAG, "decodeAsset($path) failed: ${t.message}")
            null
        }
    }
}
