/*
 * WickedSalemWitchCityTour v1.5 — Phase 9U (Session 120)
 * Copyright (c) 2026 Destructive AI Gurus, LLC. All rights reserved.
 *
 * This source code is proprietary and confidential.
 * Unauthorized copying, modification, or distribution is
 * strictly prohibited.
 */

package com.example.wickedsalemwitchcitytour.ui

import android.content.Context
import android.graphics.Bitmap
import android.util.LruCache
import android.widget.ImageView
import com.example.wickedsalemwitchcitytour.R
import com.example.wickedsalemwitchcitytour.content.model.SalemPoi
import java.io.IOException
import kotlin.math.abs

/**
 * Resolves the hero image for a POI displayed in [PoiDetailSheet].
 *
 * Resolution order:
 *   0. **Triptych** — S147 hero triptych in `assets/heroes/{poi.id}.webp`
 *      (800x200 WebP generated by tools/hero-triptych/generate_full.py).
 *      When populated for a POI, wins over every other tier.
 *   1. **poi.imageAsset** — S119 cel-shaded hero in `assets/hero/{entity_id}.webp`
 *      (1,295 POIs have this populated as of S119).
 *   2. **Category-based fallback** — hash-pinned pick from
 *      `assets/poi-icons/{category.lowercase()}/` based on POI category → folder
 *      mapping, keyed on `abs(poi.id.hashCode()) % pool.size`.
 *   3. **Red placeholder** — [R.drawable.poi_hero_placeholder_red] shown when
 *      no hero image and no category icons exist.
 */
object PoiHeroResolver {

    /**
     * S306 (PerfStabilityReview Tier 1) — hero strip is ~screen-width × 20%
     * height; heroes ship at 1152×512, so [HERO_REQ_W]×[HERO_REQ_H] yields
     * inSampleSize=1 (no visible downsample) but caps any future oversized
     * hero. The real win is the LRU below: [applyTo] was decoding the SAME
     * 2.25 MB hero TWICE per PoiDetailSheet open (bindHero + bindOverview) on
     * the main thread, uncached. The cache makes it decode once and re-binds
     * instantly on re-open. Evicted on memory pressure (no recycle → live
     * ImageViews keep their bitmap).
     */
    private const val HERO_REQ_W = 1080
    private const val HERO_REQ_H = 480

    /** ~8 MB shared LRU of decoded heroes keyed by asset path. */
    private val heroCache = object : LruCache<String, Bitmap>(8 * 1024 * 1024) {
        override fun sizeOf(key: String, value: Bitmap): Int = value.byteCount
    }

    /** Drop cached hero bitmaps under memory pressure (see SalemMainActivity.onTrimMemory). */
    fun clearCache() {
        heroCache.evictAll()
    }

    /**
     * SalemPoi.category (uppercase) → poi-icons folder mapping.
     * Used when the POI has no imageAsset (hero image).
     */
    private val categoryToFolder = mapOf(
        "WITCH_SHOP"          to "witch_shop",
        "PSYCHIC"             to "psychic",
        // S143: TOUR_COMPANIES / HISTORICAL_BUILDINGS originally pointed at
        // `tour_companies/` and `historical_buildings/` — folders that were
        // never generated, so 131 POIs fell through to the red placeholder.
        // Redirected to the closest on-disk art sets: ghost_tour/ (walking /
        // haunted / historical / night tour variants) and historic_house/
        // (colonial / literary / maritime / museum / witch-trial house).
        "TOUR_COMPANIES"      to "ghost_tour",
        "HISTORICAL_BUILDINGS" to "historic_house",
        // S299: landmarks now have their own woodcut category scenes (distinct
        // monument/marker motif) instead of reusing the historic_house set.
        "HISTORICAL_LANDMARKS" to "landmarks",
        "FOOD_DRINK"          to "food_drink",
        "LODGING"             to "lodging",
        "ENTERTAINMENT"       to "entertainment",
        "PARKS_REC"           to "parks_rec",
        "CIVIC"               to "civic",
        "EDUCATION"           to "education",
        "SHOPPING"            to "shopping",
        "WORSHIP"             to "worship",
        "HEALTHCARE"          to "healthcare",
        "OFFICES"             to "offices",
        // S143: AUTO_SERVICES and FINANCE folders exist on disk but were
        // never registered here — 52 + 5 POIs unnecessarily hit RedPlaceholder.
        "AUTO_SERVICES"       to "auto_services",
        "FINANCE"             to "finance",
        // S299: previously-unmapped categories (SERVICES 64, APARTMENT 1) hit
        // RedPlaceholder in retail; now have woodcut category scenes.
        "SERVICES"            to "services",
        "APARTMENT_BUILDING"  to "apartment_building",
        "PARKING"             to "parking",
        "FUEL_CHARGING"       to "fuel_charging",
    )

    /** Cached file listings per folder (filled lazily on first access). */
    private val folderListingCache = mutableMapOf<String, List<String>>()

    sealed class HeroResult {
        /** Path relative to `assets/` — ready for `context.assets.open()`. */
        data class AssetImage(val assetPath: String) : HeroResult()
        /** Category has no curated imagery; show the red "ASSIGN HERO" flag. */
        data object RedPlaceholder : HeroResult()
    }

    /**
     * Resolve the hero for this POI. Never throws.
     *
     * @param forceCategoryFallback S154: when true, skip Priority 0 + 1 (the
     * per-POI tiers) and go straight to the category `poi-icons` bucket. Used
     * by the stripped PoiDetailSheet rendering path for non-licensed commercial
     * POIs so we never surface a per-business hero that might reference the
     * merchant's own photography. Historic / civic / parks / worship POIs
     * still receive their curated per-POI hero via the default path.
     */
    fun resolve(
        context: Context,
        poi: SalemPoi,
        forceCategoryFallback: Boolean = false
    ): HeroResult {
        if (!forceCategoryFallback) {
            // Priority 0: S147 triptych hero, keyed on slug poi.id
            if (HeroAssetLoader.hasTriptych(context, poi.id)) {
                if (com.example.wickedsalemwitchcitytour.BuildConfig.DEBUG) {
                    com.example.locationmapapp.util.DebugLogger.d(
                        "PoiHero", "${poi.id} → tier0 triptych heroes/${poi.id}.webp",
                    )
                }
                return HeroResult.AssetImage("heroes/${poi.id}.webp")
            }

            // Priority 1: dedicated hero image from S119 generation pipeline
            poi.imageAsset?.takeIf { it.isNotBlank() }?.let { asset ->
                if (com.example.wickedsalemwitchcitytour.BuildConfig.DEBUG) {
                    com.example.locationmapapp.util.DebugLogger.d(
                        "PoiHero", "${poi.id} → tier1 imageAsset='$asset'",
                    )
                }
                return HeroResult.AssetImage(asset)
            }
        }

        // Priority 2: category-based fallback from poi-icons
        val folder = categoryToFolder[poi.category]
        if (folder == null) {
            if (com.example.wickedsalemwitchcitytour.BuildConfig.DEBUG) {
                com.example.locationmapapp.util.DebugLogger.w(
                    "PoiHero",
                    "${poi.id} → RedPlaceholder (no folder mapping for category=${poi.category})",
                )
            }
            return HeroResult.RedPlaceholder
        }

        // S154: prefer subcategory-scoped files when the POI carries a
        // subcategory that matches a file-name prefix in the folder. Keeps a
        // bakery looking like a bakery, a bar looking like a bar, etc.
        // S205: DB stores subcategory as "CATEGORY__short" (e.g. "FOOD_DRINK__cafes");
        // strip the namespace prefix before matching since icon files are named
        // by the short token alone (e.g. "cafes_witchcraft.webp"). substringAfter
        // returns the original string when "__" is not present, so legacy bare
        // tokens still work.
        val all = listingFor(context, folder)
        if (all.isEmpty()) {
            if (com.example.wickedsalemwitchcitytour.BuildConfig.DEBUG) {
                com.example.locationmapapp.util.DebugLogger.w(
                    "PoiHero",
                    "${poi.id} → RedPlaceholder (folder '$folder' empty for category=${poi.category})",
                )
            }
            return HeroResult.RedPlaceholder
        }

        val sub = poi.subcategory
            ?.lowercase()
            ?.substringAfter("__")
            ?.takeIf { it.isNotBlank() }
        val pool = if (sub != null) {
            all.filter { it.startsWith("${sub}_", ignoreCase = true) }
                .ifEmpty { all }
        } else {
            all
        }

        val idx = abs(poi.id.hashCode()) % pool.size
        val pick = "poi-icons/$folder/${pool[idx]}"
        if (com.example.wickedsalemwitchcitytour.BuildConfig.DEBUG) {
            com.example.locationmapapp.util.DebugLogger.d(
                "PoiHero",
                "${poi.id} → tier2 category-folder pick='$pick' (subcat='$sub' poolSize=${pool.size}/${all.size})",
            )
        }
        return HeroResult.AssetImage(pick)
    }

    /** Load the resolved hero into an ImageView. Safe on any IO error. */
    fun applyTo(
        context: Context,
        poi: SalemPoi,
        imageView: ImageView,
        forceCategoryFallback: Boolean = false
    ): HeroResult {
        val result = resolve(context, poi, forceCategoryFallback)
        when (result) {
            is HeroResult.AssetImage -> {
                // S306 — sampled decode + LRU (decode-once per open; was 2× full-res).
                val bitmap = heroCache.get(result.assetPath)
                    ?: SampledAssetDecoder.decode(context, result.assetPath, HERO_REQ_W, HERO_REQ_H)
                        ?.also { heroCache.put(result.assetPath, it) }
                if (bitmap != null) {
                    imageView.setImageBitmap(bitmap)
                } else {
                    imageView.setImageResource(R.drawable.poi_hero_placeholder_red)
                    return HeroResult.RedPlaceholder
                }
            }
            HeroResult.RedPlaceholder -> {
                imageView.setImageResource(R.drawable.poi_hero_placeholder_red)
            }
        }
        return result
    }

    private fun listingFor(context: Context, folder: String): List<String> {
        return folderListingCache.getOrPut(folder) {
            try {
                context.assets.list("poi-icons/$folder")
                    ?.filter { it.endsWith(".webp", ignoreCase = true) }
                    ?.sorted()
                    ?: emptyList()
            } catch (_: IOException) {
                emptyList()
            }
        }
    }
}
